### ISSUE TITLE
sass imports do not work in build-mode

### ISSUE THREAD

**Issue by mrsteele** [alicoding/react-webpack-babel#158]
If I import a css or sass file like so:
```
@import "~normalize.css/normalize";
```

... it works great with `npm run start`, however if I use `npm run build` it doesn't work and says:

```
ERROR in ./src/index.scss
Module build failed: ModuleNotFoundError: Module not found: Error: Cannot resolve module '~normalize.css/normalize'
```

**Comment by alicoding** [comment]
That's interesting because the loader is there

https://github.com/alicoding/react-webpack-babel/blob/master/webpack.production.config.js#L16-L21

Have you figured this out?

**Comment by mrsteele** [comment]
I haven't, and I thought it was interesting too.

I tried in a vanilla build of your code, and adding that line doesn't work (but only when I build).

**Comment by mrsteele** [comment]
If I run `npm run start` it works just fine.

**Comment by vydimitrov** [comment]
Hello,

I had the same issue and I found the solution here - https://github.com/webpack/extract-text-webpack-plugin/issues/63

Basically, the issue is with the ExtractTextPlugin, where you will need to provide all loaders as a single string with " ! ", something like this - ExtractTextPlugin.extract('style', 'css!postcss!sass'). 

Hope it helps, it worked for me.

**Comment by alicoding** [comment]
@vydimitrov thank you so much!
