### ISSUE TITLE
I am trying to deploy this onto heroku

### ISSUE THREAD

**Issue by Peakdrum** [alicoding/react-webpack-babel#226]
Hello,

Can I request a doc on how to deploy this app to heroku? I am trying your boilerplate step by step and I run npm run build. Then I follow heroku way of deploy a node.js app. in the website, it give me 404 error 

and this error Failed to load resource: the server responded with a status of 404 (Not Found) 

Can you please tell me how to deploy this correctly? thanks

**Comment by alicoding** [comment]
Hi (สวัสดีครับ)

The problem is that heroku required that you have server to handle the static content serving and this boilerplate doesn't have any node.js server to do that. My suggestion would be for you to create a simple [exressjs](https://expressjs.com) that serve your static content then deploy to heroku.

**Comment by alicoding** [comment]
Please reopen if you need any help :)
